### PR TITLE
Test with GHC 8.6.2 and ‘cabal-install-2.4’

### PR DESCRIPTION
**Pull request by mrkkrp**

### CODE REVIEW

**Comment by mrkkrp** [comment]
This is strange. @sboosali would you be able to investigate why it fails with GHC 8.6.1?

**Comment by sboosali** [comment]
Yes, I'll take a look.

**Comment by sboosali** [comment]
(tl;dr test failure is spurious, but i'll make sure that the tests use the right equality operation, and/or that `Wave`'s equality operation itself is correct)

So, one test fails with:

```
expected:

  Wave {..., waveChannelMask = fromList [SpeakerTopFrontRight,SpeakerFrontCenter], ...}

but got:

  Wave {..., waveChannelMask = fromList [SpeakerFrontCenter,SpeakerTopFrontRight], ...}
```

i.e. the items are reversed.

Since the field is a `Set`,

```
data Wave = {
  ...
  waveChannelMask  :: !(Set SpeakerPosition)
  ...
  }
```

the change is probably the new `containers` changing something (like the algorithm or a seed) internally. 

But, order shouldn't matter for the `Eq` instance. Other tests might be "wrong", if they're not using the right equality operation, so I'll take a look at them too.

**Comment by sboosali** [comment]
also, separately from the pull request in my fork, we should update to `new-sdist`.

**Comment by mrkkrp** [comment]
Hmm, we should get to the bottom of this and file a bug report. I’ll see about this when I get home. Maybe for now a workaround will work, but we also should make sure that in the future the situation will be resolved properly.

**Comment by sboosali** [comment]
yeah, I skimmed through the issues on `containers`, and didn't see anything
relevant. I'll check `QuickCheck`'s too, which is probably the source.

**Comment by mrkkrp** [comment]
It's strange, previously I could reproduce this locally by using `containers-0.6.0.1` as an `extra-dep` in `stack.yaml` but it doesn't work anymore.

**Comment by mrkkrp** [comment]
It looks like a bug in `containers-0.6.0.1`, I have created a minimal repro: https://github.com/mrkkrp/containers-bug. Going to report it.

**Comment by mrkkrp** [comment]
It is a bug: https://github.com/haskell/containers/issues/568.

**Comment by sboosali** [comment]
oh wow, thanks for reporting the issue (and for your tests inding it).
sorry about not doing that myself w.r.t. comaintership (I guess I assumed
it wouldn't be a bug in containers itself!).

**Comment by mrkkrp** [comment]
No problem, I just was curious WTF :)

**Comment by sboosali** [comment]
wow, it may be a `deriving Ord` bug (in the compiler itself). discussions:

https://www.reddit.com/r/haskell/comments/9ksch6/ghc_861_is_badly_broken/

https://ghc.haskell.org/trac/ghc/ticket/15696

**Pull request merged**
